/**
 * Lets TypeScript accept `import "./global.css"`.
 *
 * NativeWind's Tailwind entry point is consumed by the Metro/Babel pipeline,
 * never by tsc — so from TypeScript's point of view `../global.css` is a module
 * with no declaration, and a *side-effect* import of an undeclared module is an
 * error (TS2882) as of TypeScript 5.6. `_layout.tsx:1` has been tripping it.
 *
 * This lives in its own file rather than in `nativewind-env.d.ts` because that
 * file is generated by NativeWind and says, in its own comment, not to edit it —
 * anything added there is lost the next time it is regenerated.
 */
declare module "*.css";
